version: '3.8'

services:
  drangularapp:
    container_name: drangularappcontainer
    build: .
    image: anildursunipek/drangularapp:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet
    restart: always
  
networks:
  internalnet:
    driver: bridge